[platformio]
default_envs = microbit_arduino
src_dir = microbit

[env:microbit_arduino]
platform = nordicnrf52
board = bbcmicrobit_v2
framework = arduino
upload_protocol = mbed
upload_port = D:

[env:microbit_zephyr_ble]
platform = nordicnrf52
board = bbcmicrobit_v2
framework = zephyr
upload_protocol = mbed
upload_port = D:
build_src_filter = -<*>
